<?php
$translate = $this->plugin('translate');

$filterLocale = (bool) $this->siteSetting('filter_locale_values');
$lang = $this->lang();
?>
<div class="item-with-metadata">
<?php foreach($attachments as $attachment): ?>
    <?php $item = $attachment->item(); ?>
    <?php if (empty($item)) continue; ?>
    <div class="resource show">
    <?php if ($filterLocale):?>
		<?php echo $item->displayValues(['filters' => ['lang' => ['', $lang]]]); ?>
    <?php else:?>
		<?php echo $item->displayValues();?>
    <?php endif;?>
    <?php if ($item->itemSets()): ?>
        <div class="property">
            <h4><?php echo $translate('Item sets'); ?></h4>
            <?php foreach ($item->itemSets() as $itemSet): ?>
            <div class="value"><?php echo $itemSet->link($itemSet->displayTitle()); ?></div>
            <?php endforeach; ?>
        </div>
    <?php endif; ?>
    <?php if($item->media()): ?>
        <div class="media-list">
        <?php
        foreach ($item->media() as $media):
            echo $media->linkRaw($this->thumbnail($media, 'medium', ['title' => $media->displayTitle()]), null, [
                'class' => 'media resource'
            ]);
        endforeach;
        ?>
        </div>
    <?php endif; ?>
    </div>
<?php endforeach; ?>
</div>
